version: '2'

services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DATABASE_HOST: database
      DATABASE_USER: demo_user
      DATABASE_PASS: demo_pass
      DATABASE_NAME: demo_node_api
      DATABASE_PORT: 3306
      DATABASE_CONNECTION: mysql
    links:
      - database
  database:
    image: bitnami/mysql:8.0
    ports:
      - 3306:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=demo_pass
      - MYSQL_DATABASE=demo_node_api
